version: 2
jobs:
  build:
    macos:
      xcode: "10.0.0"

  shell: /bin/bash --login -o pipefail

  steps:
    - checkout

    - run: bundle install
    - run: bundle exec fastlane tests
    - run: xcrun instruments -w "iPhone 7 Plus (11.0) [" || true

  - store_test_results:
          path: test_output/report.xml

    - store_artifacts:
        path: /tmp/test-results
        destination: fastlane-test-results

    - store_artifacts:
        path: ~/Library/Logs/fastlane
        destination: fastlane-logs
